version: "3.3"
# /var/jenkins_home/secrets/initialAdminPassword
services:
  jenkins:
    container_name: jenkins
    restart: unless-stopped
    image: lan.jenkins.${HOSTNAME}
    # privileged: true
    build:
      context: ./
      args:
          DOCKER_GID: ${DOCKER_GID}
    environment:
      - VIRTUAL_HOST=jenkins.${HOSTNAME}.lan
      - VIRTUAL_PORT=8080
    networks:
      - subdomain_proxy_bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/var/jenkins_home
    ports:
      - 50000:50000

networks:
  subdomain_proxy_bridge:
    external: true

volumes:
  data:
