version: '2'
services:
  whoami:
    image: jwilder/whoami
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=whoami.${HOSTNAME}.lan
    networks:
      - subdomain_proxy_bridge

networks:
  subdomain_proxy_bridge:
    external: true
