version: "3.3"
services:
  plantuml:
    image: plantuml/plantuml-server:latest
    container_name: plantuml
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=plantuml.${HOSTNAME}.lan
    networks:
      - subdomain_proxy_bridge

networks:
  subdomain_proxy_bridge:
    external: true