version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - mongo_backend
    volumes:
      - ${APP_HOME}/data:/data/db
      - ${APP_HOME}/config:/data/config
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      VIRTUAL_HOST: mongodb.${HOSTNAME}.lan
      VIRTUAL_PORT: 8081
    networks:
      - mongo_backend
      - subdomain_proxy_bridge
    depends_on:
      - mongo

networks:
  subdomain_proxy_bridge:
    external: true
  mongo_backend:
    driver: bridge

