version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    environment:
      - VIRTUAL_HOST=netdata.${HOSTNAME}.lan
      - PGID=${DOCKER_GID}
    networks:
      - subdomain_proxy_bridge
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${APP_HOME}/config:/etc/netdata
      - ${APP_HOME}/lib:/var/lib/netdata
      - ${APP_HOME}/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  subdomain_proxy_bridge:
    external: true
