version: '2'
services:
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.${HOSTNAME}.lan
    networks:
      - network_proxy_bridge

networks:
  network_proxy_bridge:
    external: true
